apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-resource-deployer
  labels:
    app: k8s-resource-deployer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-resource-deployer
  template:
    metadata:
      labels:
        app: k8s-resource-deployer
    spec:
      containers:
      - name: k8s-resource-deployer
        image: python:3.9
        command: ["sleep"]
        args:
        - "9000"
        ports:
        - containerPort: 80
        resources: {}