apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-resource-deployer
  name: k8s-resource-deployer
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: k8s-resource-deployer
  type: NodePort