apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-hello
  name: flask-hello-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32080
  selector:
    app: flask-hello
  type: NodePort