---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-deployer
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs: ["list", "get", "create", "patch", "update"]

- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs: ["list", "get", "create", "patch", "update"]

- apiGroups:
  - ""
  resources:
  - services
  verbs: ["list", "get", "create", "patch", "update"]