apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-resource-deployer
  name: k8s-resource-deployer
  #namespace: UPDATE_ME_WITH_REQUIRED_NAMESPACE
spec:
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-resource-deployer
  type: NodePort