---
apiVersion: v1
kind: Namespace
metadata:
  name: backend-team

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-deployer
  namespace: backend-team

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-deployer
  namespace: backend-team
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: k8s-deployer
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: k8s-deployer
  namespace: backend-team
